### ISSUE TITLE
HmIP-SCI

### ISSUE THREAD

**Issue by chanlee84** [twendt/homey-matic#100]
Hi twendt,

ich hätte mal wieder ein interessantes Gerät, dass ich gerne verwenden möchte --> HmIP-SCI

Würde mich sehr freuen, wenn du das einbinden könntest. Werde dann natürlich wieder testen ;-)

Hier noch zwei Links mit mehr Info's zum Gerät.
https://www.homematic-ip.com/service/downloads.html?id=713&p=product
https://de.elv.com/elv-homematic-ip-kontakt-schnittstelle-hmip-sci-bausatz-153158

Danke & Gruß
chanlee

**Comment by twendt** [comment]
Das sollte kein Problem sein.

**Comment by chanlee84** [comment]
Alles klar. Dann bestell ich mir das Teil. Danke ;-)

**Comment by twendt** [comment]
Das war der 100. driver. Du kannst gerne testen. sobald du das Gerät hast.

**Comment by chanlee84** [comment]
Oh, kleines Jubiläum ;-) Ich gebe Bescheid, wenn ich ihn getestet habe. Danke ;-)

**Comment by chanlee84** [comment]
Heute gekommen und getestet --> funktioniert einwandfrei

**Comment by twendt** [comment]
Super, danke
