### ISSUE TITLE
HM-Sec-Sir-WM - Kanal 4 nicht vorhanden

### ISSUE THREAD

**Issue by dirkg173** [twendt/homey-matic#102]
Hallo Timo,

anstelle der HmIP-ASIR-2 habe ich mir doch die HM-Sec-Sir-WM zugelegt.
Allerdings fehlt der Homey Implementierung im Vergleich zu Homematic eine Funktion.
In Homematic besteht die Möglichkeit über Kanal 4 zwischen:
- Alarm aus
- Alle Sensoren scharf (extern scharf)
- Außensensoren scharf (intern scharf)

zu wählen.

Je nach aktivierter Optionen, lassen sich die 3 anderen Kanäle aktivieren oder halt nicht.
In den folgenden Screenshots habe ich mal versucht die Abhängigkeiten darzustellen:

Kanal 4: Alarm aus
<img width="863" alt="HM-Sec-Sir-WM_Kanal4-1" src="https://user-images.githubusercontent.com/40319629/107630497-e6857480-6c63-11eb-836e-6c7b6a692fa1.png">

Kanal 4: Alle Sensoren scharf (extern scharf)
<img width="860" alt="HM-Sec-Sir-WM_Kanal4-2" src="https://user-images.githubusercontent.com/40319629/107630557-f8671780-6c63-11eb-92d9-d1a87a87bedf.png">

Kanal 4: Außensensoren scharf (intern scharf)
<img width="862" alt="HM-Sec-Sir-WM_Kanal4-3" src="https://user-images.githubusercontent.com/40319629/107630580-0157e900-6c64-11eb-9cfe-c26f9c782d61.png">

Hier dazu die Beschreibung aus dem Handbuch:
<img width="449" alt="Bildschirmfoto 2021-02-11 um 12 25 28" src="https://user-images.githubusercontent.com/40319629/107630807-601d6280-6c64-11eb-9e0c-24f6870a9c6a.png">

Generell ist es natürlich möglich in der Homematic WebUI Kanal 4 auf "Alle Sensoren scharf (extern scharf)" einzustellen damit auch alle 3 Geräte/Kanäle aktiviert werden können. Allerdings wird durch den Wechsel der Optionen auf Kanal 4 auch ein Quittierungston und ein Blinksignal ausgegeben.
Wenn man abends z.B. den Überwachungsmodus von [Heimdall](https://homey.app/de-de/app/com.uc.heimdall/Heimdall/) auf "Teilweise aktiviert" ändert, dann wäre es gut und von Vorteil, wenn man von der Sirene einen entsprechenden Quittierungston erhält. Dann weiß man zumindest, dass die Sirene einsatzbereit ist. Dies gilt natürlich auch für andere Status-Änderungen.

Ein weiterer Punkt ist, dass die Batterieanzeige nicht funktioniert. Auf allen 3 Kanälen wird "Low Battery" angezeigt obwohl neue Batterien eingelegt sind. In der Homematic WebUI wird der Batteriestatus auch mit "OK" angegeben.

**Comment by twendt** [comment]
Ich habe den Channel hinzugefügt. Schau mal, ob das schon funktioniert.
Die Batterieanzeige sollte jetzt auch gehen.

**Comment by dirkg173** [comment]
1. Batterieanzeige funktioniert.

2. Das Umschalten der Zustände "Alarm aus", "Alle Sensoren scharf", "Außensensoren scharf" funktioniert auch. Sogar "Alarm blockiert" kann ich über Homey aktivieren, in der Homematic WebUI ist dies nicht möglich. Ich kenne den Hintergrund dieses Zustandes allerdings nicht. Die Bedienungsanleitung ist großer Mist!
Auch wenn das Setzen der o.g. Zustände funktioniert (in Homey, CCU-Jack und WebUI), wird in Homey ein Fehler angezeigt, egal welcher Zustand aktiviert wird. Eventuell hat das was mit Punkt 4 zutun:
![IMG_1691](https://user-images.githubusercontent.com/40319629/107878147-fbb30b00-6ed0-11eb-88a3-416807f7fbb7.PNG)
![IMG_1689](https://user-images.githubusercontent.com/40319629/107878153-0077bf00-6ed1-11eb-8914-9ef9d7e45e89.PNG)

3. Was ich bisher noch nicht erwähnt hatte, die Kanäle 1-3 werden als separate Geräte installiert:
![IMG_1702](https://user-images.githubusercontent.com/40319629/107878324-002bf380-6ed2-11eb-8ae0-6f54b308ad1b.jpeg)
Nur ein Gerät wäre natürlich deutlich schöner.

4. Die Sirene wird bei der Installation auch als Steckdose "identifiziert". Demzufolge kann man in den Geräteeinstellungen auswählen welches Gerät eingesteckt ist:
![IMG_1701](https://user-images.githubusercontent.com/40319629/107878363-6d3f8900-6ed2-11eb-9a6b-2ac79128b9e8.PNG)
Möglicher Vorteil davon ist, dass man die Sirene über die Homey App per "Knopfdruck" einschalten und wieder ausschalten kann, wie z.B. eine Lampe.

Die Punkte 3 und 4 beeinträchtigen generell die Funktion nicht, aber es wäre schön, wenn anstelle von 3 nur 1 Gerät auftauchen würde.

**Comment by twendt** [comment]
Der invalid_ capability kommt, weil du das Gerät neu anlernen musst. Danach soz es gehen.

**Comment by twendt** [comment]
Bzgl Punkt 3 muss ich schauen, wie man das machen könnte. Ich stimme dir zu, das das besser wäre.

**Comment by dirkg173** [comment]
Die Sirene hatte ich neu in Homey angelernt. Jetzt habe ich sie auch mal aus Homematic rausgeschmissen und komplett neu angelernt (inkl. Werksreset). Dennoch kommt die Fehlermeldung mit invalid_capability. Egal welches der 3 Module bzw. welchen der 3 Kanäle ich benutze und egal in welchen Zustand ich die Sirene schalte (Alarm aus, Aussensensoren scharf, Alle Sensoren scharf, Alarm blockiert). In Homematic wird der Zustand aber korrekt umgeschaltet.

Mir ist noch ein weiterer Punkt eingefallen. Die Sirene hat einen Sabotageschutz. Wird das Gehäuse geöffnet wird der Sabotagekontakt ausgelöst. Könntest Du das auch noch hinzufügen?

**Comment by twendt** [comment]
Der Fehler sollte jetzt weg sein, ich hatte die Capability nicht registriert.
Für Sabotage habe ich nun einen Tamper Alarm hinzugefügt.

Als ein Gerät kann ich die 3 Kanäle leider nicht mehr umsetzen, weil das Gerät schon in der Version im Store verfügbar ist somit eventuell schon von Anwendern verwendet wird. Dort würde es dann nicht mehr funktionieren.

**Comment by dirkg173** [comment]
Der Fehler ist weg. 👍🏼

Bzgl. der 3 Kanäle = 3 Geräte ist echt nicht schön, vor allem auch verwirrend und unübersichtlich.
Wäre es möglich die entsprechende Datei/Dateien als Kopie entsprechend zu ergänzen, so dass ich diese dann im Code händisch austauschen könnte?
Ich weiß, ist echt viel verlangt und eigentlich sollten wir alle froh sein, dass Du die App überhaupt weiterentwickelst und das in einem super schnellen Tempo, obwohl Du eigentlich hinschmeißen wolltest. Nochmals vielen Dank dafür!!!
Ich würde Dir das auch finanziell entschädigen. Aber wenn Dir das zu viel ist, nicht praktikabel ist, ein Riesen Rattenschwanz hinter sich herziehen würde oder weil Du es einfach nicht möchtest oder was auch immer, dann ist es so, und es ist dann auch völlig ok so.

**Comment by twendt** [comment]
Ich werde mir da mal was überlegen. Am besten wäre es eventuell, wenn man beim Pairing wählen könnte, welchen Modus man verwenden möchte. Oder alle neuen Geräte verwenden nur ein Gerät und die bestehenden den alten Modus.

**Comment by dirkg173** [comment]
Das wäre echt klasse! 👍🏼
Vielen Dank!

**Comment by dirkg173** [comment]
Gibt es hierzu Neuigkeiten?

**Comment by twendt** [comment]
Leider noch nicht.
Ich habe zunächst das Update auf die sdk Version 3 gemacht. Ich würde die 0.19.0 dann auch endlich veröffentlichen.
Falls ich eine Anpassung für diese Device mache, dann kommt das erst mit der 0.20. Momentan ist mir die Anpassung zu aufwendig.

**Comment by twendt** [comment]
Ich habe die Version 0.19.0 als Testversion gepushed. Du kannst sie über folgenden Link installieren: https://homey.app/a/de.twendt.homey.matic/test/

**Comment by dirkg173** [comment]
Kein Problem, letztendlich funktioniert die Sirene ja.

Und vielen, vielen Dank für die Testversion im App-Store! Das macht alles viel einfacher!
Vielen Dank!
