### ISSUE TITLE
HM-RC-2-PBU-FM

### ISSUE THREAD

**Issue by afalter** [twendt/homey-matic#122]
Hallo,

ich wollte nach der Integration einer weiteren Komponente fragen, ich hoffe das Format ist hier richtig. Vorab noch vielen Dank für die tolle App, die Integration von Homematic in Homey ist super und war auch der Hauptgrund mir einen Homey zuzulegen ;-)

Es geht sich um den HM-RC-2-PBU-FM, das ist ein Unterputz-Taster für Markenschalter.

Hier ein Link zum Gerät:
https://www.eq-3.de/produkte/homematic/detail/homematic-funk-sender-2-fach-fuer-markenschalter-unterputzmontag.html

Ich besitze den Taster bereits und hab in an einer CCU3 in Betrieb, ich kann also gerne mit weiteren Infos oder beim Testen helfen.

Danke & Grüße
Andreas

**Comment by afalter** [comment]
Ich hab es in der Zwischenzeit geschafft einen entsprechenden neuen Treiber zu erstellen und hab dafür auch einen PullRequest erzeugt: #124

Wenn ich nichts übersehen habe könnte die Integration damit eigentlich gemacht werden. Während der Implementierung ist mir aufgefallen dass es mittlerweile wohl neue Validierungen im Homey SDK gibt, unter anderem müssen wohl die IDs von Flows mittlerweile eindeutig in der ganzen App sein. Ich würde dafür noch eine neue Issue anlegen und dafür dann auch noch einen PullRequest bereitstellen.

Ich hoffe ich kann damit die App ein bißchen unterstützen.

**Comment by twendt** [comment]
Super, ich bin über jede Hilfe dankbar, da ich leider schon lange keine Zeit mehr hatte, mich um die App zu kümmern.

**Comment by afalter** [comment]
Gerne, ich werde mal versuchen ob ich auch andere Geräte hinzugefügt bekomme.
