### ISSUE TITLE
Duplicate flow action IDs

### ISSUE THREAD

**Issue by afalter** [twendt/homey-matic#125]
With the latest version of the Homey SDK, there is a new validation check for duplicate flow action IDs on "debug" level validation.

This causes validation error in this app when running 'homey app run', it complains about:

- homematic_thermostat_set_weekprofile
- homematic_thermostat_set_mode

for the drivers

- HMIP-eTRV
- HMIP-eTRV-2
- HMIP-eTRV-B
- HMIP-eTRV-C

Naming the action ids like it is done also for other drivers with the driver ID as prefix for the action ID solves the issue. I will provide a pull request containing the fix.

**Comment by twendt** [comment]
I merged the PR. This is unfortunately a breaking change, but there is no way around it. This was valid in the past and I did not realize that when I implemented it.

Thank you very much for your help, I really appreciate it.
