### ISSUE TITLE
Many unsupported devices

### ISSUE THREAD

**Issue by langepil** [twendt/homey-matic#17]
After the announcement that Homey is now available in Germany and even supports Homematic, I immediately ordered a Homey Pro.

Now I have compared the list of compatible devices with my installed hardware and found out that some things do not work.

- HmIP-STHO
- HmIP-FROLL
- HmIP-WTH-2
- HmIP-BWTH
- HmIP-PCBS
- HmIP-STH
- HmIP-STHD

Is it possible for you to support these devices step by step? Can I support you somehow?

Thank you

**Comment by twendt** [comment]
We will look into supporting these devices. It would be great if you can test the devices then by manually installing the app with the Athom CLI.

**Comment by langepil** [comment]
Great! Thanks!
I can test the app with pleasure! Just let me know

**Comment by twendt** [comment]
I have created a branch implement-issue-17 which includes all devices. The only thing that is missing is the switch state of the HmIP-BWTH. I am not sure yet how I will implement that. It is read-only and therefore I cannot use the onoff capability. Therefore I will have to implement a custom one which also means that I have to implement the flow cards.

**Comment by langepil** [comment]
Thanks a lot! 
I'm gonna test this tonight.

But in the CCU I can switch the HmIP-BWTH! In my opinion it can be implemented as a normal switch.

**Comment by langepil** [comment]
I've been testing this whole thing a little bit now! Looks very good so far! Everything works as expected!

Only the HmIP-BWTH is unfortunately not found!

**Comment by twendt** [comment]
This BWTH is weird. How exactly is the type shown in the CCU under devices?

I checked the docs again and according to them the switch state cannot be set.

We can also discuss on Slack.

**Comment by langepil** [comment]
I'm afraid I forgot to answer you!
Unfortunately I am not active in slack!

Here is a screenshot from the device settings

![HmIP-PCBS](https://user-images.githubusercontent.com/50093063/57902133-2d182600-7868-11e9-87b7-907e2ba3cccf.png)

**Comment by langepil** [comment]
Sorry the HmIP-BWTH works so far very well!

The HmIP-PCBS is the device that unfortunately does not work!

**Comment by twendt** [comment]
Ok, I think I know the issue for the HmIP-PCBS. I will update that over the weekend and let you know.

**Comment by twendt** [comment]
I fixed the PCBS.

Considering the BWTH, are able to change the switch state from the CCU?

**Comment by langepil** [comment]
The HmIP-PCBS works perfectly!

With the HmIP-BWTH I can switch the modes. So manual, auto, boost, ....
I can't switch it on or off directly! But it doesn't work with the HmIP-STHD and the HmIP-STH either! And these are the same devices, only battery operated.

When will the devices be released for official use?

**Comment by twendt** [comment]
I just published the update.
