### ISSUE TITLE
HmIP-SWDO-I not loading anymore

### ISSUE THREAD

**Issue by TermiTV** [twendt/homey-matic#22]
Since the latest Update to 0.13.0 my HmIP-SWDO-I can't get loaded. (Device stuck booting up)

`<device name="TFK Terasse Tuer" address="XXX" ise_id="1281" interface="HmIP-RF" device_type="HmIP-SWDO-I" ready_config="true">
<channel name="TFK Terasse Tuer:0" type="30" address="XXX:0" ise_id="1282" direction="UNKNOWN" parent_device="1281" index="0" group_partner="" aes_available="false" transmission_mode="AES" visible="true" ready_config="true" operate="true"/>
<channel name="TFK Terasse Tuer" type="37" address="XXX:1" ise_id="1310" direction="SENDER" parent_device="1281" index="1" group_partner="" aes_available="false" transmission_mode="AES" visible="true" ready_config="true" operate="true"/>
</device>`
![IMG_0189](https://user-images.githubusercontent.com/7591588/58477474-e8d43200-8153-11e9-84bc-6c48ff4e6f71.jpeg)

**Comment by twendt** [comment]
I renamed the folder for the driver. I have to check if I missed something.
Have you tried to delete and re-add the deivce?

**Comment by twendt** [comment]
Does it work after Pairing it again? Another user reported that it worked after pairing.

I will not change the folder names again in the future. Sorry for the inconveniences. I didn't know that it would break existing devices.

**Comment by TermiTV** [comment]
I did a rePair and now its working again! Thank You! ;)
