### ISSUE TITLE
Request for a few Homematic devices

### ISSUE THREAD

**Issue by sebi28** [twendt/homey-matic#23]
Hi,

Would you add support for a few more devices, please? It would be nice to use the following devices with the Homey:
HM-PB-2-FM
HM-LC-Sw4-Ba-PCB
HM-PB-2-WM55-2
HM-LC-Sw4-DR

Thanks!
Sebastian

**Comment by Ranzkarl** [comment]
Thanks for the Homematic application. It really works like a charm for the supported devices.
I would like to add one more device to the "wanted-list": HM-LC-Bl1-FM
It is kind of the same device as the HM-LC-Bl1PBU-FM but without the internal switch but supposed to be used with a "normal blind switch".

**Comment by twendt** [comment]
I will look into them. They won't make it into the next release though as that will be published soon.

**Comment by sebi28** [comment]
Thanks for your support!

**Comment by twendt** [comment]
I implemented all 6 devices in branch 0.15.0. It would be great if you are able to test them by manually installing the app using that branch.

**Comment by Ranzkarl** [comment]
Hi, thanks for the quick realization ;)
Attached are the test results: 
HM-SEC-SD - can be added successfully but throws an error message (Network transmission error) during the discovery. Will be added successfully anyhow and works fine
HM-LC-Bl1-FM - works perfectly

One general "issue" I have is setting the slider of the position of shutters / jalousies to "0" or "100" does not work. it's working for 1-99% but 0 and 100 needs to be manually set by using the "up" and "down" arrows. "tapping" on the fully closed or fully opened icon results in "failed to set value" error message,

Thanks

Marc

**Comment by sebi28** [comment]
Thanks for helping! It's looking very good!

Just a few things which aren't affecting the functionality:
- App version shows v0.14.1
- Image for HM-LC-Sw4-Ba-PCB missing

What I've successfully tested so far:
HM-LC-Sw4-Ba-PCB and HM-LC-Sw4-DR: turning on and off
HM-PB-2-WM55-2:  Button 1 and 2 ok, short and long ok

I have not tested the HM-PB-2-FM switch so far.

Could you add the HM-Sen-MDIR-O-2, HmIP-BSM, and may be the HM-ES-TX-WM, too? I guess the HM-ES-TX-WM might be a bit more complicated to implement.

Again, thanks for support!

**Comment by twendt** [comment]
@Ranzkarl I need to look at the issue with the position. That should be fixed before I release it. The issue with the discovery might have been a network issue. That should not be related to the device driver.

@sebi28 I always update the version right before I do the release as I usually not know the version before and also because I keep forgetting it. :-)

The new devices will be added to the next release. I have to look into them first. I added extra issues for each of them.

**Comment by sebi28** [comment]
Now, I've tested the HM-PB-2-FM and it's working fine.

Perfect and thanks for extending the app!

**Comment by twendt** [comment]
I didn't get to do anything during the week. I hope to find the time over the weekend and implement the final fixes. The branch that will be released in the end will be based on the mqtt branch which itself is based on 0.15.0.

**Comment by twendt** [comment]
Released with 0.15.0
