### ISSUE TITLE
homematic shutters not listed in Amazon Alexa

### ISSUE THREAD

**Issue by Ranzkarl** [twendt/homey-matic#30]
Hi Timo,

The Homematic roller shutters are not „detected“ from Alexa when searching for Smarthome devices, so it‘s not possible to control a percentage level via Alexa voice controls.

Can you please check and let me know?

Thanks

Marc

**Comment by twendt** [comment]
I think Homey does not support the shutters with Alexa. My Z-Wave devices are also not listed.
