### ISSUE TITLE
HmIP-FBL

### ISSUE THREAD

**Issue by chanlee84** [twendt/homey-matic#33]
Hi,
could you add support for the HmIP-FBL, please?

Thx

**Comment by twendt** [comment]
Added the device in the 0.16.0 branch. Would you be able to test by manualy installing from the source branch?
I am not sure how exactly the LEVEL_2 datapoint is working. I left it out for now and implemented is with the same functionality as the HmIP-BROLL, but I am sure that LEVEL_2 is somehow required.

**Comment by chanlee84** [comment]
Thanks for implementation. 
It works, but when the shutter is in a end position (up or down), then its drive a little bit into the other direction.

Greetings

**Comment by twendt** [comment]
Hmm, I need your help in finding a solution for this. Can you play around with the values in the Homematic Web UI? From the device description it has 2 level values, I need to understand what exactly they are doing.
If you are in the Homey Slack then we can discuss it there as well.

**Comment by chanlee84** [comment]
Ok, i will test some settings this week. You will hear from me.

**Comment by chanlee84** [comment]
Now i played with some settings in the Homematic WebUI. I adjust the time for the lamellar adjustment of the  blinds from 2 seconds to 0 seconds. Now it works perfect.

This controller is primary for blinds. I use it for two shutters with a separating relay, because the HmIP-BROLL and HmIP-FROLL do not work with seperating relais (automatic end position detection does not work with relay).

Thank you for implementing this one ;-)

Greetings

**Comment by twendt** [comment]
Thank. I am not sure though if I should change something or not.

**Comment by chanlee84** [comment]
It works perfectly. I think you do not change anything.

**Comment by twendt** [comment]
Thanks for testing it.
