### ISSUE TITLE
More Devices

### ISSUE THREAD

**Issue by llaaccssaapp** [twendt/homey-matic#34]
Can you please add support for the following Devices:
HM-LC-Sw1-Pl-DN-R5 
HM-ES-PMSw1-Pl-DN-R5 
HM-RC-8 
HM-Sen-RD-O 

thank you for your help

**Comment by twendt** [comment]
I am planning to implement the devices with the next release.

**Comment by twendt** [comment]
I close this issue. Please check the linked issues for more details on each device.
