### ISSUE TITLE
HM-Sen-RD-O

### ISSUE THREAD

**Issue by twendt** [twendt/homey-matic#38]
#34

**Comment by twendt** [comment]
Implemented, but needs verification from user.

**Comment by llaaccssaapp** [comment]
How can i test this? I don't see a version 0.16 on my homey. Should i use the code from 0.16 branch and install it with the athom-cli direct?

**Comment by llaaccssaapp** [comment]
I installed via athom tool. After adding a HM-Sen-RD-O device, the app is crashing. Restarting is not helping. Only uninstall and reinstalling helps to fix.

**Comment by twendt** [comment]
Thanks for testing this. I am very sorry for the inconveniences though. I think deleting the device would have gotten the app working again.

If possible, would you be able to do "athom app run" instead of "athom app install". Then you will see the error message and you can post it here.

Unfortunately I don't see the issue in the code without an error message.

**Comment by llaaccssaapp** [comment]
I will test again asap (with run instead of install). Thank you for the fast update.

**Comment by llaaccssaapp** [comment]
With the latest change it works. Thank you very much for this new devices.

**Comment by twendt** [comment]
Release with 0.16.0
