### ISSUE TITLE
HmIP-BRC2

### ISSUE THREAD

**Issue by LutzHein** [twendt/homey-matic#41]

**Comment by twendt** [comment]
It is implemented in branch 0.17.0. Please test it if possible.

**Comment by chanlee84** [comment]
This devices works now with homey. The device have the same issue with HmIP-WRC2.
Fix: https://github.com/twendt/homey-matic/issues/46#issuecomment-561841463

**Comment by chanlee84** [comment]
For each additional switch, a program must be created once in the ccu. After that it can be deleted again.
