### ISSUE TITLE
HmIP-FSM and HmIP-FSM 16

### ISSUE THREAD

**Issue by drbiosignals** [twendt/homey-matic#42]
Thank you very much for your work and all your efforts. Is it possible to add support for these 2 devices?
Thank you in advance

**Comment by twendt** [comment]
It is implemented in branch 0.17.0. Please test it if possible.

**Comment by chanlee84** [comment]
Works fine. I tested it with HmIP-FSM.

**Comment by drbiosignals** [comment]
HmIP-FSM16 also works fine. Thank you for all your erfforts
