### ISSUE TITLE
Homematic and HomeyKit

### ISSUE THREAD

**Issue by samclark22** [twendt/homey-matic#43]
Hello, I’ve added a device (HM-PB-2-WM55-2) using the Homematic app.

This device appears in the Homey, but apparently it is not recognized by HomeyKit and therefore not passed on to HomeKit. What can I do?

**Comment by samclark22** [comment]
The developer of HomeyKit wrote:

> That device doesn't have any capabilities, which is required for HomeyKit to be able to support it. It might work if the developer of the Homematic app adds the button capability to the device.

Can this feature be added?

**Comment by twendt** [comment]
It is true that it does not have any capabilities. It only has flow cards. This is normal for button devices.
