### ISSUE TITLE
HMIP-WRC2?

### ISSUE THREAD

**Issue by ukr42** [twendt/homey-matic#46]
Hello,

the HMIP-WRC6 is supported and working well - any chance to add the smaller HMIP-WRC2 switch as well?

**Comment by twendt** [comment]
I will implement it with the next release.

**Comment by ukr42** [comment]
Great, thank you!

**Comment by twendt** [comment]
It is implemented in branch 0.17.0. Please test it if possible.

**Comment by chanlee84** [comment]
I tried to test it, but homey does not find it.

**Comment by twendt** [comment]
I think I know what is wrong. I called the driver HmIP-WRC2 instead of HMIP-WRC2. I will fix that tonight.

**Comment by twendt** [comment]
The rename is in. Can you test it again?

**Comment by chanlee84** [comment]
Now I can add the device to homey. But there is no function when I press the buttons. I build some flows with short / long press of button 1 or 2.

**Comment by twendt** [comment]
Hmm, I don't see anything obvious in the code. Is there any error in the log?

**Comment by chanlee84** [comment]
I tested the switch with homematic now to make sure it works --> works good.
Where can i find the logs?
I have tried this one --> https://github.com/irritanterik/homey-realtime-logpage

No log entries regarding the switch when i press buttons. My testflow don't start.

**Comment by twendt** [comment]
You can run the app using  `athom app run` instead of `athom app install`. Then you will see the log from the app.
In the settings menu of the app there is also a Get Log button.

**Comment by chanlee84** [comment]
Ok, i can't find any error in the log,

**Comment by twendt** [comment]
Unfortunately I have no idea why it is not working. I have to get the device myself and test it then.

**Comment by twendt** [comment]
I got the device today. It does work in Homey. The issue was in the CCU in my case. For whatever reason I had to create a program in the CCU for each button. Before I did tat the light on the button also never turned green. Also in the CCU it did not show any update.
The funny thing is that I could delete the programs again afterwards and it still works.

**Comment by chanlee84** [comment]
Ok, i can confirm that issue. Now it works. I have tested the HmIP-BRC2 -> same issue.
Your workaround works for both devices.

**Comment by chanlee84** [comment]
For each additional switch, a program must be created once in the ccu. After that it can be deleted again.
