### ISSUE TITLE
HM-Sec-WDS-2 Water-Sensor

### ISSUE THREAD

**Issue by totti1171** [twendt/homey-matic#61]
HM-Sec-WDS-2 

Water-Sensor

![49_hm-sec-wds](https://user-images.githubusercontent.com/42803032/67949464-0c5e4580-fbe8-11e9-8687-39031a72a886.png)

**Comment by twendt** [comment]
I added this as HM-Sec-WDS to branch 0.17.0. It would be nice if you are able to test it by manually installing it.
