### ISSUE TITLE
HmIP-SLO

### ISSUE THREAD

**Issue by twendt** [twendt/homey-matic#63]

**Comment by drbiosignals** [comment]
Vielen Dank, ich kann bestätigen. Ich kann bestätigen, dass es sehr gut funktioniert.
Gibt es die Möglichkeit, alle Helligkeitswerte für Flows verfügbar haben (current, average, minimum oder maximum)? 

Nochmals Vielen Dank für Deine Bemühungen

**Comment by twendt** [comment]
Ich schau mal, wie ich die weiteren Werte implementiert bekomme. Das wird aber ein neues Pairing benötigen. Erstelle also noch nicht zu viele Flows damit.

**Comment by drbiosignals** [comment]
Vielen Dank!

**Comment by twendt** [comment]
Ich habe mal einen Versuch gemacht. Schau mal, ob es funktioniert. Kann aber sein, dass es jetzt gar nicht mehr geht.
Du musst das Gerät neu einbinden.

**Comment by drbiosignals** [comment]
Nochmals Vielen Dank, beim HmIP-SLO zeigen sich alle Werte richtig. 
Bei dieser Version habe ich trotzdem ein komisches Problem. Man kann einige Geräte (z.B. HmIP-FSM, HmIP-BSM) ein und ausschalten, es erfolgt trotzdem kein Update im Homematic Status (in Homey manchmal auch nicht). Nach kurzer Zeit stürzt die App ab. Homematic, Homey, MQTT Servers habe ich alle neu gestartet. Nach dem downgrade in die alte Version verschwindet das Problem sofort.
Das Gerät habe ich entfernt und neu eingebunden. 
Ich nutze PIVCCU3, aber das sollte an sich kein Problem sein.
Vielleicht hat es mit der neuesten Version einiger node_modules zu tun, die jetzt neu heruntergeladen werden müssen.

**Comment by twendt** [comment]
Kann du die app mal run `homey app run` starten? Dann bekommen wir eventuell eine Fehlermeldung. Bei mir scheint das Problem nicht aufzutreten.
Ich habe versucht die modules zu vergleichen und es scheinen die gleichen Versionen verwendet zu werden. Um es ganz auszuschließen könntest du das ganze node_modules Verzeichnis aus der alten Version in die neue kopieren und es damit testen.

PIVCCU3 habe ich noch nicht verwendet, ich nutze RaspberryMatic. Allerdings glaube ich nicht, dass es daran liegt.

**Comment by drbiosignals** [comment]
Du hast recht. Es hat nichts mit node_modules zu tun aber mit dem HmIP-SLO.
Nach dem Einbinden des Gerätes kommt diese Fehlermeldung 

2020-04-22 14:40:45 [err] [ManagerDrivers] [HmIP-SLO] { Error: invalid_flow_card_id

und anschließend
--- WARNING: de.twendt.homey.matic HAS RECEIVED A MEMWARN (1/24) 
Nach der 24-igsten Warnung wird die App pausiert.

Noch eine zusätzliche Info, bei dem SWSD (auch bei der letzten Version hinzugefügt) kommt zusätzlich diese Fehlermeldung

[Homematic] Failed to set capability  homematic_swsd_state for device   Error: invalid_capability
xxxx

Vielen Dank

**Comment by drbiosignals** [comment]
Wir können auch auf die vorherige Version des HmIP-SLO zurückgehen. Wenn jemand einen anderen Wert braucht könnte beim drivers/HmIP-SLO/device.js auf CURRENT_ILLUMINATION oder AVERAGE_ILLUMINATION oder MAX_ / MIN_ wechseln.

**Comment by twendt** [comment]
Die MEMWARN Meldungen machen mir Sorgen. Das ist leider ein Feature vom Homey. Da kann ich nichts machen. Die App wird durch die vielen Geräte leider immer größer. Verwendest du zu Anbindung MQTT? Damit ist es deutlich besser als mit der direkten Verbindung per XMLRPC und BINRPC. Bei mir ist es mit der 4.2.0-rc2 auch nochmal etwas besser geworden.

Den Fehler im SWSD habe ich glaube ich gelöst. Da waren die falschen Capabilities in der driver.js eingetragen. Das sollte jetzt passen.

Den Fehler im SLO sehe ich irgendwie nicht. Die FlowCard IDs sind aus meiner Sicht alle korrekt. Ich hätte da aber schon gerne alle Werte drin. Es ist aber mein erster driver mit den SubCategories. Und da ich das Gerät nicht habe, kann ich das natürlich nicht testen.

**Comment by drbiosignals** [comment]
Ich verwende MQTT und bis jetzt hatte ich bei Homeymatic mit ca. 25 Geräten ein memory footprint von ca. 20 Mb, gar nicht so schlecht.
Danke für fixing SWSD. Mit den subcategories kann ich gerne testen, wenn Du nochmals probieren willst.
