### ISSUE TITLE
HmIP-BDT 

### ISSUE THREAD

**Issue by dewenni** [twendt/homey-matic#65]
It would be great if the HmIP-BDT could be implemented.
Thanks!

**Comment by twendt** [comment]
I added the device to the 0.17.0 branch. Would you be able to install 0.17.0 manually and test the implementation?

**Comment by dewenni** [comment]
thanks a lot!
I have installed branch 0.17.0 and tested it.

- [x] find every HmIP-BDT during device install
- [x] device icon
- [x] switch on
- [ ] switch off => ! failed to set value
- [x] change dimmer value
- [x] status change if controlled by CCU

looks good except for turning device off. In that case you get an error message "! failed to set value"

**Comment by twendt** [comment]
Thanks for the intensive testing. Could you post the error message from the log? You can either get it from the App Settings page or by running the app with `homey app run` instead of `homey app install`. It seems like there is an issue with the value conversion.

Does dim to 0 actually work?

**Comment by dewenni** [comment]
dim to 0 works.

here the log message from the app for switch off command
Set LEVEL failed for device - Value 0.0

**Comment by twendt** [comment]
I changed the convert function, please try it again.

**Comment by dewenni** [comment]
now it works in general.
But at the beginning the behavior was a bit strange.
After adding devices, every device showed "switched on" state although the devices were off.
It was also not possible to switch off / on the devices with the button. 
After I have used the dim function one time, everything worked fine.
Also the switch on/off button worked after that. 

So maybe there is one small thing left with the initial status?

**Comment by twendt** [comment]
I implemented a debug log message to the device to be able to see value that is being retrieved from the device. Could you try it again and post the value here? Then I can change the convert function accordingly.

**Comment by LukasBombach** [comment]
Hey there, I'd like to test the app with my tbd, but I'm fairly new to homematic, can you tell me how I can use this branch on my homey?
