### ISSUE TITLE
HmIP-BSM

### ISSUE THREAD

**Issue by dewenni** [twendt/homey-matic#66]
It would be great if the HmIP-BSM could be implemented.
Thanks!

**Comment by dewenni** [comment]
sorry, it is already implemented

**Comment by twendt** [comment]
I just got a crash report for this device. I tried to fix the issue in 0.18.1 and published it to https://homey.app/a/de.twendt.homey.matic/test/

Would you be able to test it?

**Comment by chanlee84** [comment]
Ich kann den testen. Hab ihn im Einsatz. Gebe nachher Bescheid.

**Comment by twendt** [comment]
@chanlee84 Konntest du das Gerät testen?

**Comment by chanlee84** [comment]
Ahhh, natürlich. Ja hab getestet und es tut was es soll.

**Comment by twendt** [comment]
Ok,sehr gut, dann werde ich die 0.18.1 heute einreichen und die weiteren Geräte erst mit der 0.19 einbauen.

**Comment by twendt** [comment]
Fixed with 0.18.1
