### ISSUE TITLE
HmIP-SWSD

### ISSUE THREAD

**Issue by silber1983** [twendt/homey-matic#68]
Kannst du bitte den Rauchmelder HmIP-SWSD hinzufügen?
Andere kurze Frage: Wie komme ich zur Version 0.17.0?

![104_hm-sec-sd-2](https://user-images.githubusercontent.com/62384379/77067343-19d46a80-69e5-11ea-9f84-8e6251ec53c1.png)

Danke,
Thomas

**Comment by twendt** [comment]
Die 0.17.0 ist noch nicht released, aber du kannst sie manuell mit dem homey-cli installieren.

Was genau soll aus Homey mit dem Rauchmelder möglich sein?

Ich würde folgende Status melden:
Off, Primary, Intrusion, Secondary

Als Kommando würde ich nur ALRAM_OFF implementieren.

Ist das OK?

**Comment by twendt** [comment]
Ich habe das Gerät im 0.17.0 branch hinzugefügt. Wäre es möglich, dass du die 0.17.0 manuell installierst? Das Gerät war deutlich komplizierter als erwartet und ich bin mir nicht sicher, ob es funktioniert und so auch vernünftig verwendbar ist.

**Comment by Schimonka** [comment]
Hey! Habe ebenfalls das Gerät und wollte es ausprobieren. Aller Versionen deiner HomematicIP. App konnte ich manuell über den homeyCli zum laufen bringen, nur die 0.17.0 stürzt immer ab und ist somit nicht funktionsfähig. MQTT läuft mit der 0.16.0 sonst stabil bei mir! 

Grüße Simon 

![3C8F67D2-9268-4866-A58B-535886141A2F](https://user-images.githubusercontent.com/69915402/92083008-a329fe80-edc5-11ea-9db2-2ab325d4112b.png)
