### ISSUE TITLE
Add device HMiP-BROLL

### ISSUE THREAD

**Issue by redschumi** [twendt/homey-matic#7]
Would be cool if you can add the Shutter device HMiP-BROLL.

Thanks in Advance.

Wolfgang

**Comment by redschumi** [comment]
and forgot

HmIP-SWDO-I

Thanks again.

**Comment by twendt** [comment]
Thank you for your request. We will put in on our list. Would you be able to install the manually for testing? That way we can make sure that it works before we release the update.

**Comment by redschumi** [comment]
Thanks for quick reply. If you are German we can write in German also. :-)
I´m able to test, get my new homey tomorrow. So if you're ready let me know it.

**Comment by bjwelker** [comment]
HmIP-SWDO-I is now in only HMIP-BROLL is missing

**Comment by redschumi** [comment]
thanks a lot for updating.
when do you think that HMIP-BROLL will be available? 
Because that would be the more important thing

**Comment by redschumi** [comment]
Short info: I don´t see the HmIP-SWDO-I only HmIP-SWDO. But these are different.

**Comment by twendt** [comment]
I pushed branch add-hmip-broll, could you try and install it manually from that branch? Unfortunately I am not able to test it myself as I don't have the device.
You can also join the Homey Slack channel for further discussions.

**Comment by bjwelker** [comment]
With the next AppStore Update the devices are in. Or installieren the GitHub Version.

**Comment by redschumi** [comment]
OK, thanks. Will install Github Version, but in Github there is no HMiP-BROLL. Right?

**Comment by twendt** [comment]
Please use the branch add-hmip-broll. That includes a first implementation of it. Since I don't have the device I would appreciate feedback.

**Comment by redschumi** [comment]
Will do it on weekend. I’ll give you feedback ASAP.

**Comment by redschumi** [comment]
installed it on homey, I can see the new devices in the app, but where do I have to setup the ip-adresses in the app?

**Comment by twendt** [comment]
You don't have to setup any IP addresses. The app should discover your CCUs automatically.

**Comment by twendt** [comment]
I updated the branch, I missed to put the capabilities in. You need to delete and pair the device again for the change to take affect.

**Comment by twendt** [comment]
We are currently preparing to release a new update to the store. I have merged this into master. It would be great if you can give feedback if it works.

**Comment by redschumi** [comment]
Sorry, don’t own the homey anymore. 
It has to less advantages for me. 
But devices works.

**Comment by twendt** [comment]
Ok, thanks for testing. I will close the issue as I have submitted the update to version v0.12.0 which includes both devices.
