### ISSUE TITLE
HM-RC-4

### ISSUE THREAD

**Issue by sgedaniel** [twendt/homey-matic#73]
Ich habe mehrere HM-RC-4 Fernbedienungen, die ich leider in Homey noch nicht nutzen kann.
Können diese noch hinzugefügt werden?
![image](https://user-images.githubusercontent.com/64057878/79825741-2eb46d00-839a-11ea-9ea1-bda7dc7e2de7.png)

**Comment by twendt** [comment]
Kein Problem, ich baue sie heute Abend in der 0.17.0 ein.

**Comment by sgedaniel** [comment]
Vielen Dank.

**Comment by twendt** [comment]
Das Gerät ist nun im 0.17.0 implementiert. Kannst Du es testen?

**Comment by sgedaniel** [comment]
Würde ich gerne machen, ich weis nur nicht wie ich die 0.17.0 auf meinen homey bekomme.

**Comment by twendt** [comment]
Das ist ja ein sehr einfaches Gerät, da gehe ich davon aus, dass es schon funktionieren wird.
