### ISSUE TITLE
HmIP-SRH

### ISSUE THREAD

**Issue by crashbone47** [twendt/homey-matic#74]
Hallo,

ist es möglich den Fenstergriffsensor HmIP-SRH zu integrieren?

![Homematic - Fenstergriffsensor - SRH_UM](https://user-images.githubusercontent.com/65019441/81402211-42e5c180-9131-11ea-844c-5bcd79097f57.jpg)

Vielen Dank
crash

**Comment by chanlee84** [comment]
An dem wäre ich auch interessiert. Wäre dann auch bereit zum Testen.

Grüße

**Comment by twendt** [comment]
Ist im 0.18.0 branch implementiert.

**Comment by chanlee84** [comment]
Eben angekommen und getestet --> erfolgreich

**Comment by twendt** [comment]
Released with 0.18.1
