### ISSUE TITLE
HmIP-BRA

### ISSUE THREAD

**Issue by crashbone47** [twendt/homey-matic#76]
Ich bitte um Integration des Schalters:

HmIP-BRA

Vielen Dank
crash

**Comment by twendt** [comment]
Der taucht in der Doku nicht auf. Ich habe den im 0.18.0 branch mal wie einen HmIP-WRC2 implementiert.

**Comment by chanlee84** [comment]
Das scheint mir nur eine Tasterwippe für diverse HmIP Schalter zu sein.

https://de.elv.com/homematic-ip-tasterwippe-fuer-markenschalter-mit-pfeilen-153001

**Comment by twendt** [comment]
Released with 0.18.1
