### ISSUE TITLE
HM-LC-Sw4-DR2

### ISSUE THREAD

**Issue by crashbone47** [twendt/homey-matic#77]
Hallo,
 
auch der folgende fehlt noch:

HM-LC-Sw4-DR2

Der HM-LC-Sw4-DR steht in der Liste, aber über diesen wird der mit der 2 am Ende nicht gefunden. Vielen Dank
crash

**Comment by twendt** [comment]
Ich habe den HM-LC-Sw4-DR-2 jetzt zum HM-LC-Sw4-DR hinzugefügt.
Die Änderung ist im 0.18.0 branch.

**Comment by twendt** [comment]
Released with 0.18.1
