### ISSUE TITLE
HM-WDS30-TO

### ISSUE THREAD

**Issue by mcfetz** [twendt/homey-matic#80]
Hi zusammen,

Wäre es möglich noch den Temperaturfühler HM-WDS30-TO hinzuzufügen? 

Vielen lieben Dank,
Daniel

**Comment by mcfetz** [comment]
Hab das Device gerade mal selbst reingepatcht. Läuft. Kann/darf ich das hier einchecken?

**Comment by twendt** [comment]
Du kannst mir gerne einen PR schicken. Bitte den 0.18.0 branch als target verwenden.

**Comment by twendt** [comment]
Ich gehe mal davon aus, dass es sich um den HM-WDS30-T-O handelt, dieser ist nun im 0.18.0 branch implementiert.

**Comment by twendt** [comment]
Released with 0.18.1

**Comment by mcfetz** [comment]
Huhu. Funktioniert prima! Vielen lieben Dank!
