### ISSUE TITLE
HmIP-SRH und allgemeine Frage

### ISSUE THREAD

**Issue by chanlee84** [twendt/homey-matic#85]
Hi twendt,

ich hätte da mal wieder etwas zum Einbauen. Und zwar den Fenstergriffsensor HmIP-SRH.
Wäre cool, wenn du den integrieren könntest. Werde die Integration dann natürlich wieder testen.

Jetzt noch die allgemeine Frage. Nutzt du den Homey eigentlich noch und kommt noch ab und zu das ein oder andere Update für deine Homematic App?

Würd mich freuen, was von dir zu hören.

Grüße
chanlee

**Comment by twendt** [comment]
Ja, ich bin noch ein sehr zufriedener Nutzer von meinem Homey.

Leider habe ich in letzter Zeit sehr wenig Zeit dafür gehabt, an der App zu arbeiten. Es zeichnet sich auch nicht ab, dass sich das ich nächster Zeit ändern wird.

Es tut mir Leid, dass ich keine besseren Neuigkeiten habe.

**Comment by chanlee84** [comment]
Ok, schade das zu hören. Dann muss ich mal schauen, wie ich das HM Gerät eingebunden bekomme.
Ich hoffe, dass du irgendwann mal wieder dazu kommst. Die App läuft nämlich echt super auf dem Homey :)

Grüße
chanlee

**Comment by dirkg173** [comment]
@twendt, wäre es für Dich eventuell eine Option einen anderen Programmierer mit ins Boot zu nehmen der Dich unterstützt? Wenn ja, dann würde ich nämlich einen Aufruf in der Community starten.
Ich nutze Deine App momentan zwar nicht, aber eigentlich nur weil einige Geräte nicht unterstützt werden und mir es zu unsicher ist auf eine App zu vertrauen deren letztes Update über ein Jahr her ist.

**Comment by twendt** [comment]
@chanlee84 Ich habe den HmIP-SRH in der 0.17.0 hinzugefügt. Schau mal, ob es funktioniert. Wenn es funktioniert, dann würde ich die 0.17.0 zur Prüfung an Athom geben.

@dirkg173 Ich wäre sogar froh, wenn da jemand unterstützen würde. Welche Geräte fehlen denn für deine Umgebung? In der 0.17.0 sind sehr viele neue Geräte enthalten. Wenn da noch welche fehlen, dann kann ich sie für die 0.18 einplanen.

**Comment by chanlee84** [comment]
Hey Klasse ;-) Ich kann den vermutlich erst am Mittwoch testen. Hab mir am Freitag erst einen als Ersatz für den HM-SEC-RHS bestellen müssen, da der kaputt ging. Ich gebe dir so schnell wie möglich Bescheid.

Danke dir.

**Comment by chanlee84** [comment]
Installation lief durch und App funktioniert noch ;-)

**Comment by twendt** [comment]
Ich habe den HmIP-SRH wieder rausgenommen und die 0.17.0 nun eingereicht. Der HmIP-SRH kommt dann mit der 0.18.0, wenn du getestet hast. Der 0.18.0 branch existiert bereits mit der Änderung.

**Comment by chanlee84** [comment]
Alles klar.

**Comment by dirkg173** [comment]
@twendt, mir ging es hauptsächlich um das Funkmodul für den Garagentorantrieb von Hoermann HmIP-MOD-HO, aber das hast Du ja jetzt schon mit integriert. Vielen Dank dafür! 👍🏼

**Comment by twendt** [comment]
@dirkg173 Noch ist es nicht drin, aber wenn du es benötigst, dann würde ich es in der 0.18.0 einbauen.

**Comment by dirkg173** [comment]
Das wäre klasse! 👍🏼

**Comment by twendt** [comment]
Die 0.17.1 ist schon live.

**Comment by chanlee84** [comment]
Und wurde schon installiert ;-)

**Comment by chanlee84** [comment]
zur Version 0.18: Wenn ich die als ZIP lade und per CLI installiere, stürzt die App nach ein paar Sekunden auf dem Homey ab.
Da ich das schonmal in der 0.17er hatte, habe ich festgestellt, dass das Verzeichnis "node_modules" fehlt. Habe das noch von der 0.15er Version und das mal in die 0.18er Version kopiert und dann installiert. Damit tut es.
Ist das beabsichtigt, dass das jetzt fehlt?

**Comment by twendt** [comment]
Das ist so gewollt. Das Verzeichnis gehört nicht ins Git. Einfach in dem Verzeichnis `npm install` starten. Dann werden sie installiert.

Ich werde heute Abend Mal schauen, ob ich sie über Athom zum Testen bereitstellen kann und dort auch updaten kann.

**Comment by chanlee84** [comment]
Aso, ok. Danke für den Tipp. Hat funktioniert. Bin halt kein Entwickler :)

**Comment by twendt** [comment]
Die aktuelle Developmentversion von 0.18.0 ist jetzt hier installierbar: https://homey.app/a/de.twendt.homey.matic/test/

**Comment by chanlee84** [comment]
Sehr cool. Gleich mal installiert. Morgen kommt übrigens der Fenstergriffsensor. Berichte dann, wenn getestet.
