### ISSUE TITLE
Can't install new Versions

### ISSUE THREAD

**Issue by Schimonka** [twendt/homey-matic#87]
Hey!

I always get the same Error message during installing the new versions of the Homematic app as you can see in the picture.
Same with Version 17.1 or 18.0.

![Homeatic IP](https://user-images.githubusercontent.com/69915402/98486046-47dc1880-221b-11eb-8740-57c016da8fbf.jpg)

**Comment by twendt** [comment]
That might be an issue with your local setup. I never tried it on Windows.

Version 0.17.1 is actually available at the following link as I published it to Athom for certification:
https://homey.app/de-de/app/de.twendt.homey.matic/Homematic/test/

**Comment by twendt** [comment]
0.17.1 is now live.

**Comment by Schimonka** [comment]
Yes, I see! It works.... Thanks a lot!!!
