### ISSUE TITLE
HMIP-PS

### ISSUE THREAD

**Issue by twendt** [twendt/homey-matic#89]

**Comment by twendt** [comment]
@dirkg173 Das Gerät ist nun auch im 0.19.0 branch enthalten und kann getestet werden.

**Comment by dirkg173** [comment]
Ich habe den Zwischenstecker (noch) nicht, werde mich melden.

**Comment by twendt** [comment]
Ich habe mir selber gestern 2 bestellt.

**Comment by twendt** [comment]
Ich habe das Herz bekommen und es funktioniert.
