### ISSUE TITLE
HmIP-SMO

### ISSUE THREAD

**Issue by crashbone47** [twendt/homey-matic#90]
Hallo,

Bitte noch den HmIP-SMO (ohne -A) hinzufügen.

Ist wie der mit dem A am Ende nur eine andere Farbe. Bei der Suche nach dem mit A findet er den anderen nicht.

Vielen Dank!

**Comment by twendt** [comment]
Ich habe den HmIP-SMO nun zu dem driver für den HmIP-SMO-A hinzugefügt.
Du kannst es mit dem branch-0.19.0 testen.
