### ISSUE TITLE
HmIP-STE2-PCB

### ISSUE THREAD

**Issue by dirkg173** [twendt/homey-matic#91]
Hi twendt,
bitte den o.g. Temperatursensor hinzufügen. Ist ein neues Produkt und momentan noch nicht lieferbar, hat also Zeit.

Weitere Infos sind auf der [elv.de ](https://de.elv.com/elv-homematic-ip-komplettbausatz-temperatursensor-mit-externen-fuehlern-2-fach-hmip-ste2-pcb-155614?fs=4000041829&c=690)Seite zu finden.

Vielen Dank!

VG
Dirk

**Comment by twendt** [comment]
Das Gerät taucht leider in der aktuellen Doku mit Stand 24.7.2020 noch nicht auf, daher habe ich da noch keine Infos über die verwendeten Kanäle.

**Comment by dirkg173** [comment]
Habe ich gestern auch zum ersten Mal im ELV-Newsletter gesehen und ist momentan auch nur vorbestellbar.
In welcher Doku muss man denn nachschauen? Dann würde ich Dich informieren wenn die Infos zum Gerät verfügbar sind?

**Comment by twendt** [comment]
Ich nutze die Doku `Homematic IP Devices Technical Documentation` unter Script.

https://www.homematic-ip.com/service/downloads.html

**Comment by dirkg173** [comment]
Ok, danke, ich werde von Zeit zu Zeit mal reinschauen und Dich gegebenenfalls informieren.

**Comment by dirkg173** [comment]
Hi Timo,
das "Homematic IP Devices Technical Documentation" wurde am 15.12.2020 aktualisiert. Trotzdem finde ich den Temperatursensor nicht, nicht mit der Suchfunktion (das Dokument scheint nicht vollständig "geOCRt" su sein) und zwischen den letzteren Einträgen 169 - 190 auch nicht (ist echt keine Freude bei über 12.000 Seite danach zu suchen). Im Homematic-Forum wird über den Temperatursensor auch noch nicht wirklich aktiv diskutiert.
In dem [Changelog](https://www.eq-3.de/downloads/software/firmware/ccu3-firmware/CCU3-Changelog.3.55.5.pdf) für Firmwares, letzte FW 3.55.5 vom 09.12., habe ich den Sensor auch nicht finden können.
Ist das normal das Produkte bereits angeboten werden (allerdings nach wie vor mit langen Lieferzeiten) bevor diese unterstützt werden?

**Comment by twendt** [comment]
Es steht in der neuen Doku drin, unter Nummer 81 auf Seite 6482.

**Comment by dirkg173** [comment]
Mit PDF Expert (iOS) habe ich es jetzt auch per Suche finden können. Chrome und Safari (MacBook & iPad) waren mit der Suche scheinbar völlig überfordert, sorry.
Werde den Sensor dann bestellen. Kannst Dir mit der Implementierung dennoch Zeit lassen, die Lieferzeit beträgt aktuell noch ca. 2 Wochen.
Danke Dir!

**Comment by dirkg173** [comment]
Hi Timo,
habe das Modul jetzt hier und funktionsfähig an die CCU angelernt.
Brauchst Du irgendwelche Informationen von mir?
Kanal 1 = Temperaturfühler 1
Kanal 2 = Temperaturfühler 2
Kanal 3 = Temperaturdifferenz zwischen TF 1/Kanal1 und TF2/Kanal2

**Comment by dirkg173** [comment]
Hi Timo,
hatte überhaupt nicht gesehen dass Du das Modul bereits integriert hattest, vielen Dank dafür!!!

Zugefügt werden zwei Geräte, Kanal 1 und Kanal 2, ich denke das ist auch völlig ok so. Den Kanal 3 kann man problemlos berechnen lassen.
Das einzige was "stört", beide Geräte zeigen den Parameter "Luftfeuchtigkeit" mit einem "-" an. In CCU-Jack steht zu den beiden Kanälen folgendes:

<img width="586" alt="Bildschirmfoto 2021-03-19 um 17 05 24" src="https://user-images.githubusercontent.com/40319629/111809680-87a3c280-88d5-11eb-90b5-199ed8856feb.png">

**Comment by twendt** [comment]
Ich habe die Luftfeuchtigkeit rausgenomen.

**Comment by dirkg173** [comment]
Hi Timo,
könntest Du den 3. Kanal doch noch hinzufügen?
Außerdem wäre es schön, wenn alle 3 Kanäle in einem Gerät dargestellt werden könnten. Ist das möglich?
