### ISSUE TITLE
HmIP-FDT

### ISSUE THREAD

**Issue by AFGGU** [twendt/homey-matic#93]
Hi,
I want to switch from qivicon to homey. But I have a lot of HmIP-FDT (eQ-3 Homematic IP Dimmaktor Unterputz) in my house.
Could you please add this device?
(maybe its quite the same as HmIP-BDT )

Thank you in advance!

**Comment by twendt** [comment]
I will put that on the list. It should be an easy one to implement.

**Comment by twendt** [comment]
I added it to the 0.19.0 branch. Do you already have your Homey and would be able to test it?

**Comment by AFGGU** [comment]
Hi,
I just got my Homey. But im waiting for the CCU (if im right i need a CCU as "Gateway"?)
Plus, I would need a short description how to install a branch

**Comment by AFGGU** [comment]
Hey,
i have them now connected on the ccu3. and have my homey
how do i test it, now?

**Comment by twendt** [comment]
You can install the new release via the following link: https://homey.app/a/de.twendt.homey.matic/test/

**Comment by AFGGU** [comment]
Hi,
unfortunately its not working, yet.

"Device is not reachable"

What i see
Error Message:
![image](https://user-images.githubusercontent.com/76728006/113691599-e0909a80-96cc-11eb-8393-9049bb543fb0.png)


Everything is empty in details:
![image](https://user-images.githubusercontent.com/76728006/113691552-d4a4d880-96cc-11eb-8cc1-f7f94379f819.png)



Example, working HMIP-SWDO
![image](https://user-images.githubusercontent.com/76728006/113691427-afb06580-96cc-11eb-8c4e-6da2b0884e3d.png)

**Comment by twendt** [comment]
Sorry, there was a bug from the sdk 3 update. I published a new version 0.19.1. Please try again.

**Comment by AFGGU** [comment]
Yes! It’s working :-)

thank you
