### ISSUE TITLE
HmIP-SMI55

### ISSUE THREAD

**Issue by Lodda57** [twendt/homey-matic#94]
Hello Timo,

I have two motion detector HmIP-SMI55. The motion detector HmIP-SMI is available in the Homematic App, but the HmIP-SMI55 is not there and with HmIP-SMI it doesn`t work.
Please, can you integrate this motion detector ?

Greatings
Lothar

**Comment by twendt** [comment]
Hi Lothar,

I will implement it with the next release.

Timo

**Comment by twendt** [comment]
I added it to the 0.19.0 branch

**Comment by Lodda57** [comment]
Hi Timo,

thank you for your speed work.

Greatings

Lothar

Am 05.01.2021 00:00 schrieb twendt: 

> I added it to the 0.19.0 branch 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/twendt/homey-matic/issues/94#issuecomment-754273836
[2]
