### ISSUE TITLE
HmIP-DRSI1

### ISSUE THREAD

**Issue by Mannsi89** [twendt/homey-matic#96]
Hallo Timo ,
Großes Lob für deine Arbeit. Ich würde gerne den Taster HmIP-DRSI1 integrieren. Währe klasse, wenn du diesen hinzufügen könntest. 
Viele Grüße 
Simon

**Comment by twendt** [comment]
Ich habe den im 0.19.0 branch hinzugefügt. Wäre es möglich, dass du den branch manuell installierst und das Gerät testest?

**Comment by Mannsi89** [comment]
Hallo Timo, vielen dank! Sorry das die Antwort etwas dauert, aber Das Gerät war nicht lieferbar. Jetzt ist es da und eingebaut. den branch habe ich installiert. Allerdings crasht die app nach der installation. Vielleicht kannst du mir helfen.

**Comment by twendt** [comment]
Hast `npm install` im Verzeichnis der App gestartet?

**Comment by Mannsi89** [comment]
Ja die App wurde auch installiert und dann bekomme ich die Meldung "Die App funktioniert nicht mehr und in der App steht " Die App funktioniert nicht mehr "

**Comment by twendt** [comment]
Kannst mal `homey app run` starten und mir dann die Fehlermeldung schicken.

**Comment by Mannsi89** [comment]
✓ Plugin `compose` finished
✓ Validating app...
✓ Homey App validated successfully against level `debug`
Homey Offline

-> Meldung Homey App "App Crashed during loading"

**Comment by twendt** [comment]
War das ein `homey App run` oder `homey app install`? Da sollten noch mehr Meldungen kommen.

**Comment by Mannsi89** [comment]
homey App run
✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `compose`...
[AppPluginCompose] Added Driver `HM-CC-RT-DN`
[AppPluginCompose] Added Driver `HM-ES-PMSw1-DR`
[AppPluginCompose] Added Driver `HM-ES-PMSw1-Pl`
[AppPluginCompose] Added Driver `HM-ES-TX-WM`
[AppPluginCompose] Added Driver `HM-LC-Bl1-FM`
[AppPluginCompose] Added Driver `HM-LC-Bl1PBU-FM`
[AppPluginCompose] Added Driver `HM-LC-Dim1PWM-CV`
[AppPluginCompose] Added Driver `HM-LC-Dim1T-DR`
[AppPluginCompose] Added Driver `HM-LC-Dim1T-FM`
[AppPluginCompose] Added Driver `HM-LC-Dim1TPBU-FM`
[AppPluginCompose] Added Driver `HM-LC-Sw1-Ba-PCB`
[AppPluginCompose] Added Driver `HM-LC-Sw1-DR`
[AppPluginCompose] Added Driver `HM-LC-Sw1-FM`
[AppPluginCompose] Added Driver `HM-LC-Sw1-Pl`
[AppPluginCompose] Added Driver `HM-LC-Sw1-Pl-CT-R1`
[AppPluginCompose] Added Driver `HM-LC-Sw1-Pl-DN-R1`
[AppPluginCompose] Added Driver `HM-LC-Sw1PBU-FM`
[AppPluginCompose] Added Driver `HM-LC-Sw2-FM`
[AppPluginCompose] Added Driver `HM-LC-Sw2PBU-FM`
[AppPluginCompose] Added Driver `HM-LC-Sw4-Ba-PCB`
[AppPluginCompose] Added Driver `HM-LC-Sw4-DR`
[AppPluginCompose] Added Driver `HM-LC-Sw4-SM`
[AppPluginCompose] Added Driver `HM-LC-Sw4-WM`
[AppPluginCompose] Added Driver `HM-MOD-Re-8`
[AppPluginCompose] Added FlowCard `HM-OU-LED16-press` for type `triggers`
[AppPluginCompose] Added FlowCard `homematic_set_led_status` for type `actions`
[AppPluginCompose] Added Driver `HM-OU-LED16`
[AppPluginCompose] Added FlowCard `HM-PB-2-FM-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-PB-2-FM`
[AppPluginCompose] Added FlowCard `HM-PB-2-WM55-2-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-PB-2-WM55-2`
[AppPluginCompose] Added FlowCard `HM-PB-4-WM-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-PB-4-WM`
[AppPluginCompose] Added FlowCard `HM-PB-6-WM55-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-PB-6-WM55`
[AppPluginCompose] Added FlowCard `HM-PBI-4-FM-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-PBI-4-FM`
[AppPluginCompose] Added FlowCard `HM-RC-4-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-4`
[AppPluginCompose] Added FlowCard `HM-RC-4-2-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-4-2`
[AppPluginCompose] Added FlowCard `HM-RC-4-3-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-4-3`
[AppPluginCompose] Added FlowCard `HM-RC-8-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-8`
[AppPluginCompose] Added FlowCard `HM-RC-Key4-2-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-Key4-2`
[AppPluginCompose] Added FlowCard `HM-RC-Key4-3-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-Key4-3`
[AppPluginCompose] Added FlowCard `HM-RC-Sec4-3-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-RC-Sec4-3`
[AppPluginCompose] Added Driver `HM-Sec-Key`
[AppPluginCompose] Added Driver `HM-Sec-MDIR-2`
[AppPluginCompose] Added FlowCard `HM-Sec-RHS-changed` for type `triggers`
[AppPluginCompose] Added Driver `HM-Sec-RHS`
[AppPluginCompose] Added Driver `HM-Sec-SC`
[AppPluginCompose] Added Driver `HM-Sec-SC-2`
[AppPluginCompose] Added Driver `HM-Sec-SCo`
[AppPluginCompose] Added Driver `HM-Sec-SD`
[AppPluginCompose] Added Driver `HM-Sec-SD-2`
[AppPluginCompose] Added FlowCard `homematic_sec_sir_hm_armstate` for type `actions`
[AppPluginCompose] Added Driver `HM-Sec-Sir-WM`
[AppPluginCompose] Added FlowCard `HM-Sec-WDS-changed` for type `triggers`
[AppPluginCompose] Added Driver `HM-Sec-WDS`
[AppPluginCompose] Added FlowCard `HM-Sen-DB-PCB-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-Sen-DB-PCB`
[AppPluginCompose] Added Driver `HM-Sen-MDIR-O`
[AppPluginCompose] Added FlowCard `HM-Sen-MDIR-WM55-press` for type `triggers`
[AppPluginCompose] Added Driver `HM-Sen-MDIR-WM55`
[AppPluginCompose] Added FlowCard `HM-Sen-RD-O-turned-on` for type `triggers`
[AppPluginCompose] Added FlowCard `HM-Sen-RD-O-turned-off` for type `triggers`
[AppPluginCompose] Added Driver `HM-Sen-RD-O`
[AppPluginCompose] Added FlowCard `HM-SwI-3-FM-pressed-1` for type `triggers`
[AppPluginCompose] Added FlowCard `HM-SwI-3-FM-pressed-2` for type `triggers`
[AppPluginCompose] Added FlowCard `HM-SwI-3-FM-pressed-3` for type `triggers`
[AppPluginCompose] Added Driver `HM-SwI-3-FM`
[AppPluginCompose] Added Driver `HM-TC-IT-WM-W-EU`
[AppPluginCompose] Added Driver `HM-WDS10-TH-O`
[AppPluginCompose] Added Driver `HM-WDS100-C6-O`
[AppPluginCompose] Added Driver `HM-WDS30-T-O`
[AppPluginCompose] Added Driver `HM-WS550STH-I`
[AppPluginCompose] Added Driver `HMIP-PS`
[AppPluginCompose] Added Driver `HMIP-PSM`
[AppPluginCompose] Added Driver `HMIP-SWDO`
[AppPluginCompose] Added FlowCard `HMIP-WRC2-press` for type `triggers`
[AppPluginCompose] Added Driver `HMIP-WRC2`
[AppPluginCompose] Added Driver `HMIP-WTH`
[AppPluginCompose] Added FlowCard `homematic_thermostat_set_weekprofile` for type `actions`
[AppPluginCompose] Added Driver `HMIP-eTRV`
[AppPluginCompose] Added Driver `HmIP-ASIR`
[AppPluginCompose] Added FlowCard `HmIP-BDT-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-BDT`
[AppPluginCompose] Added FlowCard `HmIP-BRA-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-BRA`
[AppPluginCompose] Added FlowCard `HmIP-BRC2-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-BRC2`
[AppPluginCompose] Added FlowCard `HmIP-BROLL-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-BROLL`
[AppPluginCompose] Added FlowCard `HmIP-BSM-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-BSM`
[AppPluginCompose] Added Driver `HmIP-BWTH`
[AppPluginCompose] Added Driver `HmIP-DRSI1`
[AppPluginCompose] Added FlowCard `HmIP-FBL-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-FBL`
[AppPluginCompose] Added Driver `HmIP-FDT`
[AppPluginCompose] Added FlowCard `HmIP-FROLL-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-FROLL`
[AppPluginCompose] Added Driver `HmIP-FSM`
[AppPluginCompose] Added FlowCard `homematic_mod_ho_set_partial_open` for type `actions`
[AppPluginCompose] Added Driver `HmIP-MOD-HO`
[AppPluginCompose] Added Driver `HmIP-MOD-OC8`
[AppPluginCompose] Added Driver `HmIP-PCBS`
[AppPluginCompose] Added FlowCard `HmIP-RC8-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-RC8`
[AppPluginCompose] Added Driver `HmIP-SAM`
[AppPluginCompose] Added Driver `HmIP-SCI`
[AppPluginCompose] Added FlowCard `HmIP-SLO-illuminance-current` for type `triggers`
[AppPluginCompose] Added FlowCard `HmIP-SLO-illuminance-average` for type `triggers`
[AppPluginCompose] Added FlowCard `HmIP-SLO-illuminance-highest` for type `triggers`
[AppPluginCompose] Added FlowCard `HmIP-SLO-illuminance-lowest` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-SLO`
[AppPluginCompose] Added Driver `HmIP-SMI`
[AppPluginCompose] Added FlowCard `HmIP-SMI55-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-SMI55`
[AppPluginCompose] Added Driver `HmIP-SMO-A`
[AppPluginCompose] Added Driver `HmIP-SPI`
[AppPluginCompose] Added FlowCard `HmIP-SRH-changed` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-SRH`
[AppPluginCompose] Added Driver `HmIP-STE2-PCB`
[AppPluginCompose] Added Driver `HmIP-STH`
[AppPluginCompose] Added Driver `HmIP-STHD`
[AppPluginCompose] Added Driver `HmIP-STHO`
[AppPluginCompose] Added Driver `HmIP-SWD`
[AppPluginCompose] Added Driver `HmIP-SWDM`
[AppPluginCompose] Added Driver `HmIP-SWDO-I`
[AppPluginCompose] Added Driver `HmIP-SWO-PR`
[AppPluginCompose] Added FlowCard `HmIP-SWSD-changed` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-SWSD`
[AppPluginCompose] Added FlowCard `HmIP-WRC6-press` for type `triggers`
[AppPluginCompose] Added Driver `HmIP-WRC6`
[AppPluginCompose] Added FlowCard `homematic_thermostat_set_weekprofile` for type `actions`
[AppPluginCompose] Added Driver `HmIP-eTRV-2`
[AppPluginCompose] Added FlowCard `homematic_thermostat_set_weekprofile` for type `actions`
[AppPluginCompose] Added Driver `HmIP-eTRV-B`
[AppPluginCompose] Added FlowCard `homematic_thermostat_set_weekprofile` for type `actions`
[AppPluginCompose] Added Driver `HmIP-eTRV-C`
[AppPluginCompose] Added Capability `alarm_homematic_rain`
[AppPluginCompose] Added Capability `homematic_button_mod_ho_partial_open`
[AppPluginCompose] Added Capability `homematic_led_status`
[AppPluginCompose] Added Capability `homematic_measure_valve`
[AppPluginCompose] Added Capability `homematic_rhs_state`
[AppPluginCompose] Added Capability `homematic_sec_sir_hm_armstate`
[AppPluginCompose] Added Capability `homematic_swsd_alarm_button`
[AppPluginCompose] Added Capability `homematic_swsd_state`
[AppPluginCompose] Added Capability `homematic_thermostat_boost`
[AppPluginCompose] Added Capability `homematic_thermostat_mode`
[AppPluginCompose] Added Capability `homematic_thermostat_weekprofile`
[AppPluginCompose] Added Capability `homematic_water_state`
[AppPluginCompose] Added Capability `measure_homematic_gas_power`
[AppPluginCompose] Added Capability `measure_homematic_iec_power`
[AppPluginCompose] Added Capability `measure_homematic_sunshineduration`
[AppPluginCompose] Added Capability `measure_mod_ho_door_state`
[AppPluginCompose] Added Capability `meter_homematic_iec_power`
✓ Plugin `compose` finished
✓ Validating app...
✓ Homey App validated successfully against level `debug`
Homey Offline

**Comment by twendt** [comment]
Eventuell musst du nochmal `homey login` machen. Es sieht so aus, dass das cli nicht mit dem Homey reden kann.

**Comment by Mannsi89** [comment]
Lag wohl am Rechner. Neustart und alles von Anfang. Hier der Log 
─────────────── Logging stdout & stderr ───────────────
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '@twendt/binrpc'
Require stack:
- /lib/HomeMaticCCUMQTT.js
- /lib/HomeMaticDiscovery.js
- /app.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:191)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/lib/HomeMaticCCUMQTT.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/lib/HomeMaticCCUMQTT.js',
    '/lib/HomeMaticDiscovery.js',
    '/app.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js'
  ]
}

--- INFO: de.twendt.homey.matic has been killed ---

**Comment by twendt** [comment]
Jetzt liegt es am fehlenden `npm install`, dann wird es gehen.

**Comment by Mannsi89** [comment]
so hat alles geklappt. Alles installiert. und ich kann vermelden: Gerät geht! (also on/off)

**Comment by twendt** [comment]
Super, danke für das Testen.
