### ISSUE TITLE
Minimal Setup Requirements

### ISSUE THREAD

**Issue by ultimate-tester** [twendt/homey-matic#97]
Having been interested in Homematic products, I am wondering how to set it up properly with Homey before I buy anything.
I've read that the Homematic products use the BidCos protocol, something I see listed as supported.
My question now is, with the mindset of Homey being "not to have to use any manufacturer hub anymore" what is needed to get Homematic devices to work on my Homey? The readme of this repo reads as if I still need a hub and perhaps also an access point, though I'm not sure about that.

If the BidCos protocol is reverse engineered and supported, shouldn't this app handle all communication exactly as the official Homematic hub would minus all fancy (web) interfaces and app support, since Homey is the one and only interface? I.e. can I directly link a Homematic product to Homey without the use of hubs through this app?

**Comment by twendt** [comment]
The app only works with a CCU3 or RaspberryMatic. There is no support for the HmIP-HAP Access Point.

It is unfortunately not possible to connect to the devices directly from Homey via 868MHz. Homematic IP uses encryption. I have also not been able to receive any signal from the legacy BidCos devices.
