### ISSUE TITLE
HmIP-SAM (Acceleration Sensor)

### ISSUE THREAD

**Issue by dirkg173** [twendt/homey-matic#98]
Hallo Timo,

wäre es möglich den Beschleunigungssensor **HmIP-SAM** zuzufügen?
Die Notwendigen Infos stehen in der Doku auf Seite 9838 - 9841, lfd. Nr. 119.

Den Sensor habe ich noch nicht, würde ihn aber umgehend besorgen wenn Du ein OK gibst.

Vielen Dank und Gruß,
Dirk

**Comment by twendt** [comment]
Das sollte kein Problem sein.

**Comment by dirkg173** [comment]
Ok, dann werde ich den Sensor bestellen, vielen Dank!

**Comment by dirkg173** [comment]
Hi @twendt,
so, hab den Sensor da und funktioniert auch an der CCU3. Brauchst Du irgendwelche Informationen von mir?

Ist vielleicht nicht ganz so trivial. In der Homematic WebUI muss ich die **Art der Bewegungserkennung** zwischen **Erschütterung**, **Lageänderung** und **Neigungsänderung** auswählen. Was der Unterschied zwischen **Lage-** und **Neigungsänderung** ist, habe ich noch nicht ganz verstanden. Leider gibt es auch keine vernünftige Bedienungsanleitung.

Für die unterschiedlichen Bewegungserkennungen kann ich dann noch folgende Meldungen auswählen:

**Erschütterung**
Meldung im Zustand Bewegung: Keine Meldung / Ruhe / Bewegung
Meldung im Zustand Ruhe: Keine Meldung / Ruhe / Bewegung

**Lageänderung**
Meldung im Zustand Geneigt: Keine Meldung / Waagerecht / Geneigt
Meldung im Zustand Waagerecht: Keine Meldung / Waagerecht / Geneigt

**Neigungsänderung**
Meldung im Zustand Geneigt: Keine Meldung / Waagerecht / Geneigt / Senkrecht
Meldung im Zustand Waagerecht: Keine Meldung / Waagerecht / Geneigt / Senkrecht

Solltest Du weitere Infos benötigen, einfach melden.

**Comment by twendt** [comment]
Der war eigentlich ganz einfach. Er hat nur einen State MOTION mit true/false. Was das dann bedeutet, dass musst du dann in der CCU einstellen. Aus der Sicht von Homey ist das dann immer ein Motion Alarm.
Es ist im 0.19.0 branch implementiert.

**Comment by dirkg173** [comment]
Ok, kann ich das einfach drüber installieren?

**Comment by twendt** [comment]
Ja

**Comment by dirkg173** [comment]
Hallo Timo,
nach schwerem Kampf und enormer Unterstützung von Manuel, habe ich die App installiert bekommen.
Allerdings wird eine Fehlermeldung ausgegeben, die App scheint aber ordnungsgemäß zu funktionieren:
<img width="704" alt="Bildschirmfoto 2021-02-06 um 16 07 26" src="https://user-images.githubusercontent.com/40319629/107122328-66dc5c00-6897-11eb-82c6-24420cd9d0c2.png">

Was allerdings nicht funktioniert, ist die Meldung des Sensors.
Egal welche Meldekombination ich für **Erschütterung** und **Lageänderung** verwende, der Bewegung-Alarm ist in Homey immer aktiv.
In der Homematic WebUI wird z.B. unterschieden, siehe Screenshots:

<img width="841" alt="Bildschirmfoto 2021-02-06 um 17 02 04" src="https://user-images.githubusercontent.com/40319629/107123320-2b449080-689d-11eb-81ac-a0a851b020c8.png">
<img width="843" alt="Bildschirmfoto 2021-02-06 um 17 01 53" src="https://user-images.githubusercontent.com/40319629/107123323-2c75bd80-689d-11eb-9da8-70d3e39eb254.png">

Wähle ich allerdings "Keine Meldung" wird der Lage-Status nicht verändert, die LED am Sensor blinkt lediglich bzw., wenn aktiviert, ertönt ein Ton.

**Comment by twendt** [comment]
Wo die Fehlermeldung herkommt kann ich leider nicht sagen. Bei mir kommt der Fehler nicht. Eventuell musst du das homey npm updaten.

Die WebUI wird den Wert anhand der Konfiguration unterscheiden. Das ist aber nur ein Anzeigethema. In der Definition gibt es nur den Wert MOTION. Das kann ich in der App nicht so einfach machen. Waru sich der Wert nicht ändert verstehe ich leider noch nicht. Komisch ist besonders, warum er permanent aktiv ist. Das bedeutet ja, dass er den Wert ausgelesen haben muss. Der Default wäre inaktiv.

Welche Anbindung zur CCU verwendest du? MQTT oder schon den CCU Jack? Der CCU Jack hat ein Web UI. Dort kann man die Werte sehen. Für MQTT gibt es z.B. MQTT Explorer um zu sehen, welche Werte gesendet werden.

Kommen da Fehler im Log der App?

**Comment by dirkg173** [comment]
Kann man auf GitHub nicht zitieren??? 🤔

"permanent aktiv": In der WebUI wird ja auch **immer** ein Zustand angezeigt:
- Erschütterung = Erschütterung: Ja / Erschütterung: Nein
- Lageänderung = Lage: Geneigt / Lage: Horizontal
- Neigungsänderung = Neigung: -1 (immer, egal bei welcher Einstellung und Lage des Sensors. Defekt oder zu blöd die Einstellung vorzunehmen!? Egal in welche Richtung ich den Sensor neige, kommt vom Sensor auch keine Rückmeldung, Blinken oder Ton)

Anbindung MQTT
MQTT Explorer: Wo in wie muss ich den installieren?
Fehler im Log: Wenn Du die Homematic App auf dem Homey meinst, nein.

**Comment by twendt** [comment]
Technisch gesehen hat der Sensor nur die Zustände Wahr oder Falsch. Wenn du also Erschütterung konfiguriert hast, dann bedeutet Wahr `Erschütterung: Ja` und Falsch `Erschütterung: Nein`.

Stimmt denn der Zustand im Homey mit dem Zustand im Web UI überein? Wenn der Sensor mit Erschütterung seine Werte immer ändert, dann solltest du die App zunächst damit testen.

Warum die Werte dann in der Web UI nicht geändert werden, da kann ich dir leider nicht helfen, da ich den Sensor nicht kenne.

Den MQTT Explorer gibt es hier: `http://mqtt-explorer.com/`

Besser noch, du stellst auf CCU Jack um. Dazu musst du das Mosquitto AddOn von der CCU deinstallieren und dann den CCU Jack installieren. Den CCU Jack gibt es hier: [CCU Jack](https://github.com/mdzio/ccu-jack)

Anschließend kommst du auf das UI des CCU Jack: `http://ccuip:2121/ui`

**Comment by dirkg173** [comment]
Danke!
Da ich faktisch nicht weiß was ich letztendlich da an Änderungen vornehme, habe ich halt immer Schiss was kaputt zu machen, aber ich versuch es mal.

**Comment by dirkg173** [comment]
CCU Jack läuft, MQTT-Explorer installiert.

Welche Werte benötigst Du von CCU Jack UI?
Welches Protokoll muss ich auswählen, welchen Host, welchen Port muss ich beim MQTT-Explorer eingeben?

**Comment by twendt** [comment]
Für den CCU Jack benötigst du den MQTT Explorer nicht. Du kannst die Werte im UI des CCU Jack sehen. Einfach im Navigator bis zum MOTION Wert des Sensors durchklicken und dann schauen, ob sich die Werte dort ändern und mit dem Wert in Honey übereinstimmt. Wenn dem so ist, dann tut die App was sie soll.

**Comment by dirkg173** [comment]
Ich habe die ganzen Parameter in Channel 1 überprüft gehabt und natürlich nichts gefunden... 🤦🏼‍♂️
Im Verzeichnis MOTION wird der Wert bei entsprechender Lageveränderung von 0 auf 1 geändert bzw. umgekehrt.

Aktuelle Einstellungen des Sensors und Werte lt. CCU Jack UI
- Art der Bewegungserkennung: Lageänderung (welche ich benötige)
- Meldung im Zustand Geneigt: Geneigt -> Wert 1
<img width="381" alt="Bildschirmfoto 2021-02-07 um 14 47 03" src="https://user-images.githubusercontent.com/40319629/107148465-74efb280-6953-11eb-8077-4dfef3df37f9.png">

- Meldung im Zustand Waagerecht: Waagerecht -> Wert 0

<img width="382" alt="Bildschirmfoto 2021-02-07 um 14 46 52" src="https://user-images.githubusercontent.com/40319629/107148471-846efb80-6953-11eb-8155-8fa07c15cdb1.png">


Bei **alarm_motion** in Developer findet keine Statusänderung statt. Der Status ist und bleibt **true**.

**Comment by twendt** [comment]
Ich sehe leider nicht wo der Fehler ist. Kannst da Log aus der App schicken?

Indem Settings in der App muss folgendes stehen:

MQTT Port: 1883
Username: leer lassen
Password: leer lassen

**Comment by dirkg173** [comment]
OK, lt. Log steht: MQTT ist disconnected:

![IMG_1669](https://user-images.githubusercontent.com/40319629/107152270-4085f180-6967-11eb-9c60-c5666e1e92e4.jpeg)

Hier mal die Einträge von den Firewall-Einstellungen der CCU (falls es damit eventuell zutun hat):

<img width="374" alt="Bildschirmfoto 2021-02-07 um 17 08 41" src="https://user-images.githubusercontent.com/40319629/107152309-8642ba00-6967-11eb-872e-44e323714e58.png">

**Comment by twendt** [comment]
Der Connection Type steht auf mqtt laut der Meldung statt auf CCU Jack.
Eventuell muss du in den Einstellungen der App die stored Bridges löschen und den Haken bei use stored Bridges für einen Restart rausnehmen, sofern er gesetzt ist.
Am besten startest du auch den CCU Jack auf der CCU durch.
Welche anderen AddOns hast du auf der CCU noch installiert?

**Comment by dirkg173** [comment]
Ist jetzt auf CCU Jack umgestellt.

![95D71ED5-8C38-4779-896C-D7D30BDC9A96](https://user-images.githubusercontent.com/40319629/107176551-fe44ca80-69cf-11eb-95ca-ef075552f303.jpeg)

Ansonsten ist noch RedMatic und Mediola Neo Server installiert. Neo nutze ich aber nicht und könnte ich theoretisch deinstallieren.

**Comment by twendt** [comment]
Ich werde schauen, dass ich da heute Abend ein paar Logmeldungen einbaue.

**Comment by twendt** [comment]
So ich habe da ein Logging eingebaut. Du musst die App aber mit `homey app run` starten. Die Meldungen tauchen nicht in der `Get logs` Funktion in den Einstellungen auf.

**Comment by dirkg173** [comment]
Ich habe das 0.19.0 Branch heruntergeladen und per homey app run gestartet und bekomme folgende Fehlermeldung:

<img width="936" alt="Bildschirmfoto 2021-02-09 um 13 31 14" src="https://user-images.githubusercontent.com/40319629/107364203-6fbd6f80-6adb-11eb-8e28-748027379bcf.png">

Was mich wundert, das alte App hat eine Größe von 48,7 MB, die aktuelle App nur 6,95 MB.

**Comment by chanlee84** [comment]
Hast du vorher im Branch Verzeichnis ein npm install ausgeführt bzw. hast du im Branch Verzeichnis ein "node_modules" Verzeichnis?

**Comment by dirkg173** [comment]
npm install -> ja
node_modules -> nein

**Comment by chanlee84** [comment]
Dann hat das npm install nichts getan. Ich hab das vorhin kurz vorbereitet und die neue Branch hat bei mir um die 40 MB groß.
Frisch runtergeladen ist es um die 5-6 MB groß.

Mach das nochmal mit dem npm install.

**Comment by dirkg173** [comment]
@twendt, @chanlee84 hat mir bereits geholfen. Werde morgen wg. des Logs gucken und berichten.

**Comment by dirkg173** [comment]
Hier der Log:
```HmIP-SAM value: false
HmIP-SAM value: false
HmIP-SAM value: true
HmIP-SAM value: false
HmIP-SAM value: true
```

`false` wird angezeigt wenn der Sensor liegt (Waagerecht)
`true` wird angezeigt wenn der Sensor steht (Geneigt)

Bei folgenden Einstellungen:

<img width="439" alt="Bildschirmfoto 2021-02-10 um 13 24 34" src="https://user-images.githubusercontent.com/40319629/107509802-567ff600-6ba3-11eb-9e94-ede721dc69f4.png">

In Homey bleibt der Bewegungsalarm aktiv.

**Comment by twendt** [comment]
Sehr gut, dann weiss ich jetzt, was ich tun muss. Ich dachte, dass da 0 oder 1 kommen würde.
Ich baue das heute Abend schnell um und dann kannst du wieder testen.

**Comment by twendt** [comment]
Ich habe die Anpassung gemacht. Schau mal ob es geht. Ich bin mir noch nicht ganz sicher, ob es jeweils true/false als String ist oder ein echter boolean Wert.

**Comment by dirkg173** [comment]
Lageänderung und Erschütterung funktionieren wie es sein soll! 👍🏼
Mit Neigungswinkel stehe ich nach wie vor auf Kriegsfuß. Diese Variante bekomme ich unter Homematic WebUI schon nicht ans Laufen. Ob eventuell was defekt ist oder ich zu blöd... 🤷🏼‍♂️

Kannst Du also freigeben, eventuell mit einem Hinweis auf den Neigungswinkel, der eventuell von einem anderen User mal geprüft werden müsste.

Vielen Dank, Timo!

**Comment by twendt** [comment]
Super, das freut mich.
