### ISSUE TITLE
CCU Jack Connection Problem

### ISSUE THREAD

**Issue by chanlee84** [twendt/homey-matic#99]
Hi twendt,

bei der Installation von der 0.19er Branch per CLI bekomme ich folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/53170360/106805279-cdc6fe80-6666-11eb-8ae2-a3c1691d17ca.png)

App läuft aber trotzdem ohne Probleme.

Grüße
chanlee

**Comment by twendt** [comment]
Das hat nichts mit der App zu tun würde ich sagen.

**Comment by twendt** [comment]
Wenn du keinen CUxD hast,dann kannst du gerne die Anbindung über den CCU-Jack verwenden.

**Comment by chanlee84** [comment]
Wie gesagt, App läuft ohne Probleme. Habe diesen Fehler jetzt das erste Mal bekommen.
Da ich gesehen habe, dass du die 19er Branch vor 10 Tagen geupdated hast und ich mich nicht an den Fehler beim letzen Mal erinnern kann, hab ich gedacht ich lass dich teilhaben ;-)

**Comment by chanlee84** [comment]
Ok, ich stell mal um auf CCU Jack.
Wenn ich das gemacht habe, brauche ich dann noch RedMatic und den Homey Flow dort?
So wie ich das jetzt verstanden habe, dann eher nicht mehr, oder?

**Comment by twendt** [comment]
Genau, das wird dann nicht mehr benötigt. Den Mosquito musst du auch deinstallieren. Der CCU Jack beinhaltet einen MQTT Server und verwendet die gleichen Ports.

**Comment by chanlee84** [comment]
Umgestellt und scheint zu funktionieren. Morgen weiß ich dann mehr, wenn ein paar Automationen gelaufen sind.
Habe allerdings in den Logs viele Fehler. Siehe Screenshots.

![image](https://user-images.githubusercontent.com/53170360/106810057-ba1e9680-666c-11eb-94fd-a9c6e4e78ef9.png)
![image](https://user-images.githubusercontent.com/53170360/106810025-b1c65b80-666c-11eb-8f27-0cc9869223bd.png)

**Comment by chanlee84** [comment]
Ich war mal so frei und hab den Issue mal umbenannt.

Gestern abend hab ich ja erfolgreich auf CCU Jack umgestellt.
Heute habe ich den Homey auf v5 RC62 upgedated und nachdem Neustart habe ich leider Probleme, eine Verbindung hinzubekommen.
App startet sauber, Geräte werden sauber dargestellt, es tut sich aber nichts.

Im Log steht nur "Started homematic"

Ein Neustart der App bringt auch nichts.
Nach einiger Zeit habe ich mal die App deaktiviert und wieder aktiviert. Da sagt mir das Log, dass er jetzt Connected sei, tut sich aber trotzdem nichts.

Hast du da auch schon solche Erfahrungen gemacht?

**Comment by twendt** [comment]
Ich hatte die Probleme noch nicht. Ich habe heute morgen auf rc61 ulgedated. Da ging alles. Ich habe jetzt auch die rc62 angeboten bekommen und spiele das gerade ein.

**Comment by dirkg173** [comment]
Ich habe auch auf rc62 aktualisiert und habe keine Probleme, allerdings mit einer CCU3.

**Comment by chanlee84** [comment]
Also ich bekomme das nicht mehr zum laufen. Setze die App jetzt mal auf 18.1 zurück und konfiguriere MQTT neu.
Nach update ich wieder auf die aktuelle 0.19er Branch und hoffe MQTT tut dann noch.

Dann werde ich nochmals CCU Jack versuchen.

**Comment by chanlee84** [comment]
Ich habe jetzt eine Verbindung hinbekommen. Allerdings lassen sich alle Bestandsgeräte nicht bedienen.
Wenn ich sie dann lösche und neu hinzufüge funktioniert das wieder.

Gibt es da auch noch eine andere Lösung? Hattet ihr auch das Problem?

**Comment by chanlee84** [comment]
Das mit den Geräten neu einbinden bringt bei mir auch nichts. Nach einem Neustart deiner App funktioniert das auch wieder nicht.

**Comment by chanlee84** [comment]
> Ich habe auch auf rc62 aktualisiert und habe keine Probleme, allerdings mit einer CCU3.

Nutzt du auch schon CCU Jack oder machst du das noch über MQTT und Node Red?

**Comment by chanlee84** [comment]
Ich habe jetzt vermutlich eine Lösung.
Bei einem Homey oder App Neustart dauert es ewig, bis meine CCU gefunden wird und die HM-Geräte sind sehr lange nicht nutzbar.

Nutze ich "Use stored CCUS" connected er sich sofort und die HM-Geräte stehen sofort zur Verfügung.
Die Geräte musste ich dann auch nicht neu hinzufügen.

Kann man den Discovery Prozess evtl. beschleunigen? Für das erste Discovery ist es ja okay, wenn es etwas länger dauert, aber bei einem Homey Neustart ist es eigentlich nicht optimal, wenn es so lange nach Appstart dauert, bis die HM-Geräte nutzbar sind.

**Comment by twendt** [comment]
Für genau diesen Fall habe ich die Option damals eingebaut.

**Comment by chanlee84** [comment]
Hast du das bei dir dann auch aktiviert? Oder habe ich nur das Problem mit
CCU Jack? Über MQTT hatte uch das nicht.

twendt <notifications@github.com> schrieb am Do., 4. Feb. 2021, 15:36:

**Comment by dirkg173** [comment]
@chanlee84, über MQTT und Node Red.

**Comment by twendt** [comment]
Ich habe das immer an, seit ich das damals eingebaut habe. Das Problem ist damals bei einem Nutzer auch plötzlich aufgetaucht. 

Bei der Option merkt sich die App dann einfach die CCU.

Ich hätte am liebsten gar kein Discovery eingebaut, aber Athom hat drauf bestanden.

**Comment by twendt** [comment]
Es wäre aber gut, wenn die App damit umgehen könnte. Da habe ich aber noch keine Lösung gefunden.

Ich bin bei deinem Log gar nicht auf diesen Fall gekommen. Ich hätte eher vermutet, dass es an der Firewall in der CCU liegt. Im Log von gestern Abend waren lauter 500er. Das wäre ja dann ein internal Server Error vom CCU Jack. Somit hat er ja eigentlich die IP haben müssen.

**Comment by chanlee84** [comment]
> @chanlee84, über MQTT und Node Red.

Ja ok. Über die Connection geht es bei mir auch problemlos. Hatte nur die Probleme über CCU Jack.

**Comment by chanlee84** [comment]
> Es wäre aber gut, wenn die App damit umgehen könnte. Da habe ich aber noch keine Lösung gefunden.
> 
> Ich bin bei deinem Log gar nicht auf diesen Fall gekommen. Ich hätte eher vermutet, dass es an der Firewall in der CCU liegt. Im Log von gestern Abend waren lauter 500er. Das wäre ja dann ein internal Server Error vom CCU Jack. Somit hat er ja eigentlich die IP haben müssen.

Ja gestern Abend kannst ignorieren. Das hatte eher mit der CCU zu tun, weil ich da noch das MQTT Addon drauf hatte und gleiche Ports etc.
Hatte es ja danach ja problemlos zum Laufen bekommen. Erst heute morgen kam es wieder zu einem Problem, dass die Geräte nicht ansprechbar waren. Hat ja mit dem Discovery zu tun gehabt. Jetzt mit dem gesetzten Haken bei der gespeicherten CCU funktioniert das einwandfrei. Scheint dann wirklich daran zu liegen, dass er nicht auf Anhieb die CCU findet.

Stand jetzt bin ich zufrieden ;-)

**Comment by chanlee84** [comment]
Kurzer Stand --> es tut immer noch. Keine Probleme mehr. Wenn man das weiß mit dem Stored Bridge Thema, dann ist die CCU Jack Variante einwandfrei ;-) Somit Thema gegessen.
